var mongoose = require("mongoose");
var AutoIncrement = require('mongoose-sequence')(mongoose);
var mongoosePages = require('mongoose-pages');

// define the schema for our user model
var supplierSchema = mongoose.Schema({
    // supNum - AutoGenerated by mongoose-sequence:  Supplier Number e.g. 690
    name        :   String,
    code        :   String,
    info        :   {
        contact :   {
            name    :   String,
            email   :   String,
            address :   String,
            postcode:   String
        }
    },
    email       :   String,
    prevOrders  :   [String],
    schedule    :   [{
        weekStart   :   Date,
        monday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        tuesday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        wednesday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        thursday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        friday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        saturday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        },
        sunday      :   {
            available   :   Boolean,
            fromH       :   Number,
            fromM       :   Number,
            toH         :   Number,
            toM         :   Number
        }
    }],
    unavailable :   [String],
    complete    :   {type:  Boolean, default    : true}
},{
    usePushEach : true
});
mongoosePages.skip(supplierSchema);
supplierSchema.index({supNum:1, type: 1}); // Index SKU

supplierSchema.plugin(AutoIncrement, {inc_field: "supNum"});

// create the model for users and expose it to our app
module.exports = mongoose.model("Stock", supplierSchema);